Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-02eb7a4783e7e9317
      InstanceType: t2.medium
      KeyName: master
      SecurityGroupIds:sg-02cd41cfe12c94b49
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          echo "Hello, EC2 instance!"
#
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:devops
